# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `solid_cache` gem.
# Please instead update this file by running `bin/tapioca gem solid_cache`.


# See https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf
#
# pkg:gem/solid_cache#lib/solid_cache/engine.rb:6
module SolidCache
  # pkg:gem/solid_cache#lib/solid_cache.rb:13
  def configuration; end

  # pkg:gem/solid_cache#lib/solid_cache.rb:13
  def configuration=(val); end

  # pkg:gem/solid_cache#lib/solid_cache.rb:12
  def executor; end

  # pkg:gem/solid_cache#lib/solid_cache.rb:12
  def executor=(val); end

  class << self
    # pkg:gem/solid_cache#lib/solid_cache.rb:13
    def configuration; end

    # pkg:gem/solid_cache#lib/solid_cache.rb:13
    def configuration=(val); end

    # pkg:gem/solid_cache#lib/solid_cache.rb:12
    def executor; end

    # pkg:gem/solid_cache#lib/solid_cache.rb:12
    def executor=(val); end

    # pkg:gem/solid_cache#lib/solid_cache/engine.rb:8
    def railtie_helpers_paths; end

    # pkg:gem/solid_cache#lib/solid_cache/engine.rb:8
    def railtie_namespace; end

    # pkg:gem/solid_cache#lib/solid_cache/engine.rb:8
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/solid_cache#lib/solid_cache/engine.rb:8
    def table_name_prefix; end

    # pkg:gem/solid_cache#lib/solid_cache/engine.rb:8
    def use_relative_model_naming?; end
  end
end

# pkg:gem/solid_cache#lib/solid_cache/configuration.rb:4
class SolidCache::Configuration
  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:7
  def initialize(store_options: T.unsafe(nil), database: T.unsafe(nil), databases: T.unsafe(nil), connects_to: T.unsafe(nil), executor: T.unsafe(nil), encrypt: T.unsafe(nil), encryption_context_properties: T.unsafe(nil), size_estimate_samples: T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:5
  def connects_to; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:5
  def encrypt; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:25
  def encrypt?; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:5
  def encryption_context_properties; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:5
  def executor; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:21
  def shard_keys; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:17
  def sharded?; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:5
  def size_estimate_samples; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:5
  def store_options; end

  private

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:48
  def default_encryption_context_properties; end

  # pkg:gem/solid_cache#lib/solid_cache/configuration.rb:30
  def set_connects_to(database:, databases:, connects_to:); end
end

# pkg:gem/solid_cache#lib/solid_cache/connections.rb:4
module SolidCache::Connections
  class << self
    # pkg:gem/solid_cache#lib/solid_cache/connections.rb:5
    def from_config(options); end
  end
end

# pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:5
class SolidCache::Connections::Sharded
  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:8
  def initialize(names); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:27
  def assign(keys); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:6
  def consistent_hash; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:31
  def count; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:6
  def names; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:6
  def nodes; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:19
  def with(name, &block); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:23
  def with_connection_for(key, &block); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:13
  def with_each(&block); end

  private

  # pkg:gem/solid_cache#lib/solid_cache/connections/sharded.rb:36
  def shard_for(key); end
end

# pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:5
class SolidCache::Connections::Single
  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:8
  def initialize(name); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:26
  def assign(keys); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:30
  def count; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:6
  def name; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:34
  def names; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:18
  def with(name, &block); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:22
  def with_connection_for(key, &block); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/single.rb:12
  def with_each(&block); end
end

# pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:5
class SolidCache::Connections::Unmanaged
  # pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:20
  def assign(keys); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:24
  def count; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:28
  def names; end

  # pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:12
  def with(name); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:16
  def with_connection_for(key); end

  # pkg:gem/solid_cache#lib/solid_cache/connections/unmanaged.rb:6
  def with_each; end
end

# pkg:gem/solid_cache#lib/solid_cache/engine.rb:7
class SolidCache::Engine < ::Rails::Engine; end

class SolidCache::Entry < ::SolidCache::Record
  include ::SolidCache::Entry::GeneratedAttributeMethods
  include ::SolidCache::Entry::GeneratedAssociationMethods
  include ::SolidCache::Entry::Size
  include ::SolidCache::Entry::Expiration
  include ::SolidCache::Entry::Encryption
  extend ::SolidCache::Entry::Size::ClassMethods
  extend ::SolidCache::Entry::Expiration::ClassMethods

  class << self
    def clear_delete; end
    def clear_truncate; end
    def delete_by_key(*keys); end
    def id_range; end
    def in_key_hash_range(*args, **_arg1); end
    def largest_byte_sizes(*args, **_arg1); end
    def lock_and_write(key, &block); end
    def read(key); end
    def read_multi(keys); end
    def up_to_byte_size(*args, **_arg1); end
    def write(key, value); end
    def write_multi(payloads); end

    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
    def add_key_hash_and_byte_size(payloads); end
    def byte_size_for(payload); end
    def estimated_row_overhead; end
    def key_hash_for(key); end
    def key_hashes_for(keys); end
    def select_sql(keys); end
    def upsert_unique_by; end
    def without_query_cache(&block); end
  end
end

SolidCache::Entry::ESTIMATED_ENCRYPTION_OVERHEAD = T.let(T.unsafe(nil), Integer)
SolidCache::Entry::ESTIMATED_ROW_OVERHEAD = T.let(T.unsafe(nil), Integer)

module SolidCache::Entry::Encryption
  extend ::ActiveSupport::Concern
end

module SolidCache::Entry::Expiration
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::SolidCache::Entry::Expiration::ClassMethods
end

module SolidCache::Entry::Expiration::ClassMethods
  def expire(count, max_age:, max_entries:, max_size:); end

  private

  def cache_full?(max_entries:, max_size:); end
  def expiry_candidate_ids(count, max_age:, max_entries:, max_size:); end
end

module SolidCache::Entry::GeneratedAssociationMethods; end
module SolidCache::Entry::GeneratedAttributeMethods; end
SolidCache::Entry::KEY_HASH_ID_RANGE = T.let(T.unsafe(nil), Range)
SolidCache::Entry::MULTI_BATCH_SIZE = T.let(T.unsafe(nil), Integer)

module SolidCache::Entry::Size
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::SolidCache::Entry::Size::ClassMethods
end

module SolidCache::Entry::Size::ClassMethods
  def estimated_size(samples: T.unsafe(nil)); end
end

class SolidCache::Entry::Size::Estimate
  def initialize(samples:); end

  def exact?; end
  def max_records; end
  def samples; end
  def size; end

  private

  def key_hash_range; end
  def non_outlier_estimated_size; end
  def outliers_count; end
  def outliers_cutoff; end
  def outliers_size; end
  def outliers_size_count_and_cutoff; end
  def sample_range; end
  def sample_range_size; end
  def sampled_fraction; end
  def sampled_non_outlier_size; end
end

class SolidCache::Entry::Size::MovingAverageEstimate
  def initialize(samples:); end

  def exact?(*_arg0, **_arg1, &_arg2); end
  def samples; end
  def size; end

  private

  def estimate; end
  def latest_value; end
  def latest_values; end
  def previous_values; end
  def retained_estimates; end
  def retained_estimates_for_target_fraction; end
  def write_values(values); end
end

SolidCache::Entry::Size::MovingAverageEstimate::ESTIMATES_KEY = T.let(T.unsafe(nil), String)
SolidCache::Entry::Size::MovingAverageEstimate::MAX_RETAINED_ESTIMATES = T.let(T.unsafe(nil), Integer)
SolidCache::Entry::Size::MovingAverageEstimate::TARGET_SAMPLED_FRACTION = T.let(T.unsafe(nil), Float)

class SolidCache::ExpiryJob < ::ActiveJob::Base
  def perform(count, shard: T.unsafe(nil), max_age: T.unsafe(nil), max_entries: T.unsafe(nil), max_size: T.unsafe(nil)); end
end

# pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:6
class SolidCache::MaglevHash
  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:12
  def initialize(nodes); end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:20
  def node(key); end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:7
  def nodes; end

  private

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:27
  def build_lookup; end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:43
  def build_preferences(node); end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:25
  def lookup; end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:50
  def md5(*args); end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:25
  def node_count; end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:54
  def quick_hash(key); end
end

# pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:58
class SolidCache::MaglevHash::Preferences
  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:59
  def initialize(offset, skip); end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:64
  def preferred_free_slot(lookup); end

  private

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:74
  def next_slot; end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:72
  def preferred_slots; end

  # pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:72
  def rank; end
end

# Must be prime
#
# pkg:gem/solid_cache#lib/solid_cache/maglev_hash.rb:10
SolidCache::MaglevHash::TABLE_SIZE = T.let(T.unsafe(nil), Integer)

class SolidCache::Record < ::ActiveRecord::Base
  include ::SolidCache::Record::GeneratedAttributeMethods
  include ::SolidCache::Record::GeneratedAssociationMethods

  class << self
    def disable_instrumentation(&block); end
    def each_shard(&block); end
    def with_instrumenter(instrumenter, &block); end
    def with_shard(shard, &block); end

    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module SolidCache::Record::GeneratedAssociationMethods; end
module SolidCache::Record::GeneratedAttributeMethods; end
SolidCache::Record::NULL_INSTRUMENTER = T.let(T.unsafe(nil), ActiveSupport::Notifications::Instrumenter)

# pkg:gem/solid_cache#lib/solid_cache/store.rb:4
class SolidCache::Store < ::ActiveSupport::Cache::Store
  include ::ActiveSupport::Cache::Strategy::LocalCache
  include ::SolidCache::Store::Stats
  include ::SolidCache::Store::Failsafe
  include ::SolidCache::Store::Expiry
  include ::SolidCache::Store::Execution
  include ::SolidCache::Store::Entries
  include ::SolidCache::Store::Connections
  include ::SolidCache::Store::Api

  # pkg:gem/solid_cache#lib/solid_cache/store.rb:8
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store.rb:16
  def setup!; end

  class << self
    # pkg:gem/solid_cache#lib/solid_cache/store.rb:12
    def supports_cache_versioning?; end
  end
end

# pkg:gem/solid_cache#lib/solid_cache/store/api.rb:5
module SolidCache::Store::Api
  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:11
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:35
  def cleanup(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:39
  def clear(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:26
  def decrement(name, amount = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:17
  def increment(name, amount = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:9
  def max_key_bytesize; end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:154
  def adjust(name, amount, options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:164
  def adjusted_entry(value, amount, options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:118
  def delete_entry(key, **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:122
  def delete_multi_entries(entries, **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:136
  def deserialize_entry(payload, **_arg1); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:140
  def normalize_key(key, options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:44
  def read_entry(key, **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:79
  def read_multi_entries(names, **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:75
  def read_serialized_entries(keys); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:48
  def read_serialized_entry(key, **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:130
  def serialize_entries(entries, **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:126
  def serialize_entry(entry, raw: T.unsafe(nil), **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:144
  def truncate_key(key); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:52
  def write_entry(key, entry, raw: T.unsafe(nil), unless_exist: T.unsafe(nil), **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:106
  def write_multi_entries(entries, expires_in: T.unsafe(nil), **options); end

  # pkg:gem/solid_cache#lib/solid_cache/store/api.rb:71
  def write_serialized_entry(key, payload, raw: T.unsafe(nil), unless_exist: T.unsafe(nil), expires_in: T.unsafe(nil), race_condition_ttl: T.unsafe(nil), returning: T.unsafe(nil), **options); end
end

# pkg:gem/solid_cache#lib/solid_cache/store/api.rb:6
SolidCache::Store::Api::DEFAULT_MAX_KEY_BYTESIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/solid_cache#lib/solid_cache/store/api.rb:7
SolidCache::Store::Api::SQL_WILDCARD_CHARS = T.let(T.unsafe(nil), Array)

# pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:5
module SolidCache::Store::Connections
  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:8
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:37
  def connections; end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:6
  def shard_options; end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:29
  def with_each_connection(async: T.unsafe(nil), &block); end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:62
  def connection_names; end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:58
  def group_by_connection(keys); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:66
  def reading_key(key, failsafe:, failsafe_returning: T.unsafe(nil), &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:72
  def reading_keys(keys, failsafe:, failsafe_returning: T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:42
  def setup!; end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:52
  def with_connection(name, async: T.unsafe(nil), &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:46
  def with_connection_for(key, async: T.unsafe(nil), &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:98
  def writing_all(failsafe:, failsafe_returning: T.unsafe(nil), &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:82
  def writing_key(key, failsafe:, failsafe_returning: T.unsafe(nil), &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/connections.rb:88
  def writing_keys(entries, failsafe:, failsafe_returning: T.unsafe(nil)); end
end

# pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:5
module SolidCache::Store::Entries
  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:8
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:6
  def clear_with; end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:20
  def entry_clear; end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:66
  def entry_delete(key); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:72
  def entry_delete_multi(entries); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:30
  def entry_lock_and_write(key, &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:38
  def entry_read(key); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:44
  def entry_read_multi(keys); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:50
  def entry_write(key, payload); end

  # pkg:gem/solid_cache#lib/solid_cache/store/entries.rb:58
  def entry_write_multi(entries); end
end

# pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:5
module SolidCache::Store::Execution
  # pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:6
  def initialize(options = T.unsafe(nil)); end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:43
  def active_record_instrumentation?; end

  # pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:13
  def async(&block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:27
  def execute(async, &block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:47
  def setup_instrumentation(&block); end

  # pkg:gem/solid_cache#lib/solid_cache/store/execution.rb:35
  def wrap_in_rails_executor(&block); end
end

# pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:5
module SolidCache::Store::Expiry
  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:12
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def expires_per_write; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def expiry_batch_size; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def expiry_method; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def expiry_queue; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def max_age; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def max_entries; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:10
  def max_size; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:25
  def track_writes(count); end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:37
  def expire_later; end

  # pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:30
  def expiry_batches(count); end
end

# For every write that we do, we attempt to delete EXPIRY_MULTIPLIER times as many records.
# This ensures there is downward pressure on the cache size while there is valid data to delete
#
# pkg:gem/solid_cache#lib/solid_cache/store/expiry.rb:8
SolidCache::Store::Expiry::EXPIRY_MULTIPLIER = T.let(T.unsafe(nil), Integer)

# pkg:gem/solid_cache#lib/solid_cache/store/failsafe.rb:5
module SolidCache::Store::Failsafe
  # pkg:gem/solid_cache#lib/solid_cache/store/failsafe.rb:21
  def initialize(options = T.unsafe(nil)); end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/failsafe.rb:28
  def error_handler; end

  # pkg:gem/solid_cache#lib/solid_cache/store/failsafe.rb:30
  def failsafe(method, returning: T.unsafe(nil)); end
end

# pkg:gem/solid_cache#lib/solid_cache/store/failsafe.rb:15
SolidCache::Store::Failsafe::DEFAULT_ERROR_HANDLER = T.let(T.unsafe(nil), Proc)

# pkg:gem/solid_cache#lib/solid_cache/store/failsafe.rb:6
SolidCache::Store::Failsafe::TRANSIENT_ACTIVE_RECORD_ERRORS = T.let(T.unsafe(nil), Array)

# pkg:gem/solid_cache#lib/solid_cache/store/stats.rb:5
module SolidCache::Store::Stats
  # pkg:gem/solid_cache#lib/solid_cache/store/stats.rb:6
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/solid_cache#lib/solid_cache/store/stats.rb:10
  def stats; end

  private

  # pkg:gem/solid_cache#lib/solid_cache/store/stats.rb:22
  def connection_stats; end

  # pkg:gem/solid_cache#lib/solid_cache/store/stats.rb:18
  def connections_stats; end
end

# pkg:gem/solid_cache#lib/solid_cache/version.rb:4
SolidCache::VERSION = T.let(T.unsafe(nil), String)
