# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sshkit` gem.
# Please instead update this file by running `bin/tapioca gem sshkit`.


# pkg:gem/sshkit#lib/core_ext/array.rb:1
class Array
  include ::Enumerable

  # pkg:gem/sshkit#lib/core_ext/array.rb:2
  def extract_options!; end
end

# pkg:gem/sshkit#lib/core_ext/hash.rb:1
class Hash
  include ::Enumerable

  # pkg:gem/sshkit#lib/core_ext/hash.rb:2
  def symbolize_keys; end

  # pkg:gem/sshkit#lib/core_ext/hash.rb:8
  def symbolize_keys!; end
end

# pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:6
module Net::SSH; end

# pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:7
class Net::SSH::Config
  class << self
    # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:11
    def default_files; end
  end
end

module Net::SSH::Proxy; end

# pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:14
class Net::SSH::Proxy::Command
  # Ensure a stable string value is used, rather than memory address.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:16
  def inspect; end
end

#  @author Lee Hambley
#
# pkg:gem/sshkit#lib/sshkit.rb:1
module SSHKit
  class << self
    # pkg:gem/sshkit#lib/sshkit.rb:14
    def config; end

    # pkg:gem/sshkit#lib/sshkit.rb:7
    def config=(_arg0); end

    # pkg:gem/sshkit#lib/sshkit.rb:9
    def configure; end

    # pkg:gem/sshkit#lib/sshkit.rb:18
    def reset_configuration!; end
  end
end

# pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:5
module SSHKit::Backend
  class << self
    # The Backend instance that is running in the current thread. If no Backend
    # is running, returns `nil` instead.
    #
    # Example:
    #
    #   on(:local) do
    #     self == SSHKit::Backend.current # => true
    #   end
    #
    # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:18
    def current; end
  end
end

# pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:22
class SSHKit::Backend::Abstract
  extend ::Forwardable

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:36
  def initialize(host, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:105
  def as(who, &_block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:70
  def background(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:64
  def capture(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:25
  def debug(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:137
  def download!(_remote, _local = T.unsafe(nil), _options = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:25
  def error(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:78
  def execute(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:25
  def fatal(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:27
  def host; end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:25
  def info(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:25
  def log(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:51
  def make(commands = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:55
  def rake(commands = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:47
  def redact(arg); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:29
  def run; end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:59
  def test(*args); end

  # Backends which extend the Abstract backend should implement the following methods:
  #
  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:136
  def upload!(_local, _remote, _options = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:25
  def warn(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:97
  def with(environment, &_block); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:83
  def within(directory, &_block); end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:158
  def command(args, options); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:146
  def create_command_and_execute(args, options); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:138
  def execute_command(_cmd); end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:142
  def output; end

  # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:150
  def pwd_path; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:126
    def config; end

    # pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:130
    def configure; end
  end
end

# The ConnectionPool caches connections and allows them to be reused, so long as
# the reuse happens within the `idle_timeout` period. Timed out connections are
# eventually closed, forcing a new connection to be used in that case.
#
# Additionally, a background thread is started to check for abandoned
# connections that have timed out without any attempt at being reused. These
# are eventually closed as well and removed from the cache.
#
# If `idle_timeout` set to `false`, `0`, or `nil`, no caching is performed, and
# a new connection is created and then immediately closed each time. The default
# timeout is 30 (seconds).
#
# There is a single public method: `with`. Example usage:
#
#   pool = SSHKit::Backend::ConnectionPool.new
#   pool.with(Net::SSH.method(:start), "host", "username") do |connection|
#     # do stuff with connection
#   end
#
# pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:40
class SSHKit::Backend::ConnectionPool
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:43
  def initialize(idle_timeout = T.unsafe(nil)); end

  # Immediately close all cached connections and empty the pool.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:79
  def close_connections; end

  # Immediately remove all cached connections, without closing them. This only
  # exists for unit test purposes.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:74
  def flush_connections; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:41
  def idle_timeout; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:41
  def idle_timeout=(_arg0); end

  # Creates a new connection or reuses a cached connection (if possible) and
  # yields the connection to the given block. Connections are created by
  # invoking the `connection_factory` proc with the given `args`. The arguments
  # are used to construct a key used for caching.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:59
  def with(connection_factory, *args); end

  protected

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:89
  def caches; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:89
  def timed_out_connections; end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:97
  def cache_enabled?; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:93
  def cache_key_for_connection_args(args); end

  # Look up a Cache that matches the given connection arguments.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:102
  def find_cache(args); end

  # Immediately close any connections that are pending closure.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:146
  def process_deferred_close; end

  # Loops indefinitely to close connections and to find abandoned connections
  # that need to be closed.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:134
  def run_eviction_loop; end

  # Close the given `connection` immediately, assuming it responds to a `close`
  # method. If it doesn't, or if `nil` is provided, it is silently ignored. Any
  # `StandardError` is also silently ignored. Returns `true` if the connection
  # was closed; `false` if it was already closed or could not be closed due to
  # an error.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:171
  def silently_close_connection(connection); end

  # Adds the connection to a queue that is processed asynchronously by a
  # background thread. The connection will eventually be closed.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:162
  def silently_close_connection_later(connection); end

  # Cache creation needs to happen in a mutex, because otherwise a race
  # condition might cause two identical caches to be created for the same key.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:113
  def thread_safe_find_or_create_cache(key); end

  # Update cache key with changed args to prevent cache miss
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool.rb:122
  def update_key_if_args_changed(cache, args); end
end

# A Cache holds connections for a given key. Each connection is stored along
# with an expiration time so that its idle duration can be measured.
#
# pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:3
class SSHKit::Backend::ConnectionPool::Cache
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:6
  def initialize(key, idle_timeout, closer); end

  # Close all connections and completely clear the cache.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:52
  def clear; end

  # Close and remove any connections in this Cache that have been idle for
  # too long.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:36
  def evict; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:4
  def key; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:4
  def key=(_arg0); end

  # Remove and return a fresh connection from this Cache. Returns `nil` if
  # the Cache is empty or if all existing connections have gone stale.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:16
  def pop; end

  # Return a connection to this Cache.
  #
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:25
  def push(conn); end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:59
  def same_key?(other_key); end

  protected

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:65
  def closer; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:65
  def connections; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:65
  def idle_timeout; end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:73
  def closed?(conn); end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/cache.rb:69
  def fresh?(expires_at); end
end

# pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
class SSHKit::Backend::ConnectionPool::NilCache < ::Struct
  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
  def closer; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
  def closer=(_); end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:4
  def pop; end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:8
  def push(conn); end

  # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:12
  def same_key?(_key); end

  class << self
    # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
    def [](*_arg0); end

    # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
    def inspect; end

    # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
    def keyword_init?; end

    # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
    def members; end

    # pkg:gem/sshkit#lib/sshkit/backends/connection_pool/nil_cache.rb:3
    def new(*_arg0); end
  end
end

# pkg:gem/sshkit#lib/sshkit/backends/local.rb:7
class SSHKit::Backend::Local < ::SSHKit::Backend::Abstract
  # pkg:gem/sshkit#lib/sshkit/backends/local.rb:9
  def initialize(_ = T.unsafe(nil), &block); end

  # pkg:gem/sshkit#lib/sshkit/backends/local.rb:28
  def download!(remote, local = T.unsafe(nil), _options = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/local.rb:13
  def upload!(local, remote, options = T.unsafe(nil)); end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/local.rb:41
  def execute_command(cmd); end
end

# pkg:gem/sshkit#lib/sshkit/backends/abstract.rb:7
class SSHKit::Backend::MethodUnavailableError < ::SSHKit::StandardError; end

# pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:23
class SSHKit::Backend::Netssh < ::SSHKit::Backend::Abstract
  extend ::SSHKit::Backend::Netssh::LimitConcurrentStartsClass
  extend ::SSHKit::Backend::Netssh::DnsRetriable

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:87
  def download!(remote, local = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:79
  def upload!(local, remote, options = T.unsafe(nil)); end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:141
  def execute_command(cmd); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:116
  def transfer_summarizer(action, options = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:190
  def with_ssh(&block); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:201
  def with_transfer(summarizer); end

  class << self
    # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:24
    def assert_valid_transfer_method!(method); end

    # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:109
    def config; end

    # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:105
    def configure(&block); end

    # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:103
    def pool; end

    # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:103
    def pool=(_arg0); end
  end
end

# pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:30
class SSHKit::Backend::Netssh::Configuration
  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:35
  def initialize; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:31
  def connection_timeout; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:31
  def connection_timeout=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:31
  def pty; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:31
  def pty=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:45
  def ssh_options; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:33
  def ssh_options=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:32
  def transfer_method; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:39
  def transfer_method=(method); end

  private

  # Set default options early for ConnectionPool cache key
  #
  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:64
  def assign_defaults; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh.rb:52
  def default_options; end
end

# pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:113
class SSHKit::Backend::Netssh::KnownHosts
  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:114
  def initialize; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:127
  def add(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:120
  def search_for(host, options = T.unsafe(nil)); end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:134
  def known_hosts_file(path); end
end

# pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:9
class SSHKit::Backend::Netssh::KnownHostsKeys
  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:10
  def initialize(path); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:17
  def keys_for(hostlist); end

  private

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:92
  def empty_line?(scanner); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:41
  def hosts_hashes; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:41
  def hosts_hashes=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:41
  def hosts_keys; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:41
  def hosts_keys=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:47
  def parse_file; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:87
  def parse_host_hash(line); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:97
  def parse_hostlist(scanner); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:107
  def parse_key(scanner); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:71
  def parse_line(scanner, hosts_keys, hosts_hashes); end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:40
  def path; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:43
  def sha1; end

  # pkg:gem/sshkit#lib/sshkit/backends/netssh/known_hosts.rb:102
  def supported_type?(scanner); end
end

# Printer is used to implement --dry-run in Capistrano
#
# pkg:gem/sshkit#lib/sshkit/backends/printer.rb:5
class SSHKit::Backend::Printer < ::SSHKit::Backend::Abstract
  # pkg:gem/sshkit#lib/sshkit/backends/printer.rb:12
  def download!(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/printer.rb:7
  def execute_command(cmd); end

  # pkg:gem/sshkit#lib/sshkit/backends/printer.rb:14
  def test(*_arg0); end

  # pkg:gem/sshkit#lib/sshkit/backends/printer.rb:11
  def upload!(*args); end
end

# pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:4
class SSHKit::Backend::Skipper < ::SSHKit::Backend::Abstract
  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:6
  def initialize(&block); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:23
  def debug(_messages); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:14
  def download!(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:22
  def error(_messages); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:10
  def execute_command(cmd); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:21
  def fatal(_messages); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:17
  def info(_messages); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:20
  def log(_messages); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:15
  def test(*args); end

  # pkg:gem/sshkit#lib/sshkit/backends/skipper.rb:13
  def upload!(*args); end
end

# Very basic support for ANSI color, so that we don't have to rely on
# any external dependencies. This class handles colorizing strings, and
# automatically disabling color if the underlying output is not a tty.
#
# pkg:gem/sshkit#lib/sshkit/color.rb:6
class SSHKit::Color
  # pkg:gem/sshkit#lib/sshkit/color.rb:26
  def initialize(output, env = T.unsafe(nil)); end

  # Converts the given obj to string and surrounds in the appropriate ANSI
  # color escape sequence, based on the specified color and mode. The color
  # must be a symbol (see COLOR_CODES for a complete list).
  #
  # If the underlying output does not support ANSI color (see `colorize?),
  # the string will be not be colorized. Likewise if the specified color
  # symbol is unrecognized, the string will not be colorized.
  #
  # Note that the only mode currently support is :bold. All other values
  # will be silently ignored (i.e. treated the same as mode=nil).
  #
  # pkg:gem/sshkit#lib/sshkit/color.rb:41
  def colorize(obj, color, mode = T.unsafe(nil)); end

  # Returns `true` if the underlying output is a tty, or if the SSHKIT_COLOR
  # environment variable is set.
  #
  # pkg:gem/sshkit#lib/sshkit/color.rb:54
  def colorize?; end
end

# pkg:gem/sshkit#lib/sshkit/color.rb:7
SSHKit::Color::COLOR_CODES = T.let(T.unsafe(nil), Hash)

# @author Lee Hambley
#
# pkg:gem/sshkit#lib/sshkit/command.rb:9
class SSHKit::Command
  # Initialize a new Command object
  #
  # @param  [Array] A list of arguments, the first is considered to be the
  # command name, with optional variadaric args
  # @return [Command] An un-started command object with no exit staus, and
  # nothing in stdin or stdout
  #
  # pkg:gem/sshkit#lib/sshkit/command.rb:22
  def initialize(*args); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def args; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def command; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:32
  def complete?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:149
  def environment_hash; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:153
  def environment_string; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def exit_status; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:88
  def exit_status=(new_exit_status); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:54
  def failed?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:51
  def failure?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:35
  def finished?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def full_stderr; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def full_stdout; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:183
  def group(&_block); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:125
  def host; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:173
  def in_background(&_block); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:82
  def on_stderr(channel, data); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:76
  def on_stdout(channel, data); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def options; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:101
  def runtime; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:140
  def should_map?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def started; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:41
  def started=(new_started); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:37
  def started?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def started_at; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:66
  def stderr; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:71
  def stderr=(new_value); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:56
  def stdout; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:61
  def stdout=(new_value); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:46
  def success?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:49
  def successful?; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:190
  def to_command; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:106
  def to_hash; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:214
  def to_s; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:178
  def umask(&_block); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:167
  def user(&_block); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:13
  def uuid; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:129
  def verbosity; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:161
  def with(&_block); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:207
  def with_redaction; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:144
  def within(&_block); end

  private

  # pkg:gem/sshkit#lib/sshkit/command.rb:240
  def call_interaction_handler(stream_name, data, channel); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:229
  def default_options; end

  # pkg:gem/sshkit#lib/sshkit/command.rb:246
  def log_reader_deprecation(stream); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:253
  def log_writer_deprecation(stream); end

  # pkg:gem/sshkit#lib/sshkit/command.rb:236
  def sanitize_command(cmd); end

  class << self
    # allow using home directory but escape everything else like spaces etc
    #
    # pkg:gem/sshkit#lib/sshkit/command.rb:223
    def shellescape_except_tilde(file); end
  end
end

# pkg:gem/sshkit#lib/sshkit/command.rb:11
class SSHKit::Command::Failed < ::SSHKit::StandardError; end

# pkg:gem/sshkit#lib/sshkit/command_map.rb:2
class SSHKit::CommandMap
  # pkg:gem/sshkit#lib/sshkit/command_map.rb:36
  def initialize(value = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:40
  def [](command); end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:55
  def []=(command, new_command); end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:59
  def clear; end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:63
  def defaults; end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:51
  def prefix; end
end

# pkg:gem/sshkit#lib/sshkit/command_map.rb:3
class SSHKit::CommandMap::CommandHash
  # pkg:gem/sshkit#lib/sshkit/command_map.rb:4
  def initialize(defaults = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:9
  def [](key); end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:13
  def []=(key, value); end

  private

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:19
  def normalize_key(key); end
end

# pkg:gem/sshkit#lib/sshkit/command_map.rb:24
class SSHKit::CommandMap::PrefixProvider
  # pkg:gem/sshkit#lib/sshkit/command_map.rb:25
  def initialize; end

  # pkg:gem/sshkit#lib/sshkit/command_map.rb:29
  def [](command); end
end

# pkg:gem/sshkit#lib/sshkit/command_map.rb:34
SSHKit::CommandMap::TO_VALUE = T.let(T.unsafe(nil), Proc)

# pkg:gem/sshkit#lib/sshkit/configuration.rb:3
class SSHKit::Configuration
  # pkg:gem/sshkit#lib/sshkit/configuration.rb:42
  def backend; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:6
  def backend=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:79
  def command_map; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:83
  def command_map=(value); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:24
  def default_env; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:6
  def default_env=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:28
  def default_runner; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:6
  def default_runner=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:32
  def default_runner_config; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:36
  def default_runner_config=(config_hash); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:12
  def deprecation_logger; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:20
  def deprecation_output=(out); end

  # TODO: deprecate in favor of `use_format`
  #
  # pkg:gem/sshkit#lib/sshkit/configuration.rb:55
  def format=(format); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:8
  def output; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:6
  def output=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:46
  def output_verbosity; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:50
  def output_verbosity=(verbosity); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:5
  def umask; end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:5
  def umask=(_arg0); end

  # Tell SSHKit to use the specified `formatter` for stdout. The formatter
  # can be the name of a built-in SSHKit formatter, like `:pretty`, a
  # formatter class, like `SSHKit::Formatter::Pretty`, or a custom formatter
  # class you've written yourself.
  #
  # Additional arguments will be passed to the formatter's constructor.
  #
  # Example:
  #
  #   config.use_format(:pretty)
  #
  # Is equivalent to:
  #
  #   config.output = SSHKit::Formatter::Pretty.new($stdout)
  #
  # pkg:gem/sshkit#lib/sshkit/configuration.rb:74
  def use_format(formatter, *args); end

  private

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:93
  def formatter_class(symbol); end

  # pkg:gem/sshkit#lib/sshkit/configuration.rb:89
  def logger(verbosity); end
end

# pkg:gem/sshkit#lib/sshkit/coordinator.rb:3
class SSHKit::Coordinator
  # pkg:gem/sshkit#lib/sshkit/coordinator.rb:7
  def initialize(raw_hosts); end

  # pkg:gem/sshkit#lib/sshkit/coordinator.rb:12
  def each(options = T.unsafe(nil), &block); end

  # pkg:gem/sshkit#lib/sshkit/coordinator.rb:5
  def hosts; end

  # pkg:gem/sshkit#lib/sshkit/coordinator.rb:5
  def hosts=(_arg0); end

  private

  # pkg:gem/sshkit#lib/sshkit/coordinator.rb:29
  def default_options; end

  # pkg:gem/sshkit#lib/sshkit/coordinator.rb:33
  def resolve_hosts; end
end

# pkg:gem/sshkit#lib/sshkit/dsl.rb:3
module SSHKit::DSL
  # pkg:gem/sshkit#lib/sshkit/dsl.rb:5
  def on(hosts, options = T.unsafe(nil), &block); end

  # pkg:gem/sshkit#lib/sshkit/dsl.rb:9
  def run_locally(&block); end
end

# pkg:gem/sshkit#lib/sshkit/deprecation_logger.rb:4
class SSHKit::DeprecationLogger
  # pkg:gem/sshkit#lib/sshkit/deprecation_logger.rb:5
  def initialize(out); end

  # pkg:gem/sshkit#lib/sshkit/deprecation_logger.rb:10
  def log(message); end
end

# pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:5
module SSHKit::Formatter; end

# pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:7
class SSHKit::Formatter::Abstract
  extend ::Forwardable

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:14
  def initialize(output, options = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:39
  def <<(obj); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:12
  def colorize(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:21
  def debug(message); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:21
  def error(message); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:21
  def fatal(message); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:21
  def info(message); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:25
  def log(message); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:31
  def log_command_data(command, _stream_type, _stream_data); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:35
  def log_command_exit(command); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:27
  def log_command_start(command); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:10
  def options; end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:10
  def original_output; end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:11
  def read(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:11
  def rewind(*args, **_arg1, &block); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:21
  def warn(message); end

  # pkg:gem/sshkit#lib/sshkit/formatters/abstract.rb:43
  def write(_obj); end
end

# pkg:gem/sshkit#lib/sshkit/formatters/black_hole.rb:5
class SSHKit::Formatter::BlackHole < ::SSHKit::Formatter::Abstract
  # pkg:gem/sshkit#lib/sshkit/formatters/black_hole.rb:7
  def write(_obj); end
end

# pkg:gem/sshkit#lib/sshkit/formatters/dot.rb:5
class SSHKit::Formatter::Dot < ::SSHKit::Formatter::Abstract
  # pkg:gem/sshkit#lib/sshkit/formatters/dot.rb:7
  def log_command_exit(command); end

  # pkg:gem/sshkit#lib/sshkit/formatters/dot.rb:11
  def write(_obj); end
end

# pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:5
class SSHKit::Formatter::Pretty < ::SSHKit::Formatter::Abstract
  # pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:25
  def log_command_data(command, stream_type, stream_data); end

  # pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:35
  def log_command_exit(command); end

  # pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:18
  def log_command_start(command); end

  # pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:10
  def write(obj); end

  protected

  # pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:44
  def format_message(verbosity, message, uuid = T.unsafe(nil)); end

  private

  # pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:52
  def write_message(verbosity, message, uuid = T.unsafe(nil)); end
end

# pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:8
SSHKit::Formatter::Pretty::LEVEL_COLORS = T.let(T.unsafe(nil), Array)

# pkg:gem/sshkit#lib/sshkit/formatters/pretty.rb:7
SSHKit::Formatter::Pretty::LEVEL_NAMES = T.let(T.unsafe(nil), Array)

# pkg:gem/sshkit#lib/sshkit/formatters/simple_text.rb:5
class SSHKit::Formatter::SimpleText < ::SSHKit::Formatter::Pretty
  # Historically, SimpleText formatter was used to disable coloring, so we maintain that behaviour
  #
  # pkg:gem/sshkit#lib/sshkit/formatters/simple_text.rb:8
  def colorize(obj, _color, _mode = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/formatters/simple_text.rb:12
  def format_message(_verbosity, message, _uuid = T.unsafe(nil)); end
end

# pkg:gem/sshkit#lib/sshkit/host.rb:8
class SSHKit::Host
  # pkg:gem/sshkit#lib/sshkit/host.rb:25
  def initialize(host_string_or_options_hash); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:67
  def ==(other_host); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:64
  def eql?(other_host); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:68
  def equal?(other_host); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:89
  def first_suitable_parser(host); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:56
  def hash; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def hostname=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:13
  def key=(new_key); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:21
  def keys; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:17
  def keys=(new_keys); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:52
  def local?; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:74
  def netssh_options; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def password; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def password=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def port; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def port=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:85
  def properties; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def ssh_options; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def ssh_options=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:70
  def to_s; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:11
  def transfer_method; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:46
  def transfer_method=(method); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def user; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:10
  def user=(_arg0); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:60
  def username; end
end

# pkg:gem/sshkit#lib/sshkit/host.rb:142
class SSHKit::HostWithPortParser < ::SSHKit::SimpleHostParser
  # pkg:gem/sshkit#lib/sshkit/host.rb:152
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:148
  def port; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/host.rb:144
    def suitable?(host_string); end
  end
end

# @private
#
# pkg:gem/sshkit#lib/sshkit/host.rb:160
class SSHKit::HostWithUsernameAndPortParser < ::SSHKit::SimpleHostParser
  # pkg:gem/sshkit#lib/sshkit/host.rb:167
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:170
  def port; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:164
  def username; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/host.rb:161
    def suitable?(host_string); end
  end
end

# @private
#
# pkg:gem/sshkit#lib/sshkit/host.rb:198
class SSHKit::HostWithUsernameParser < ::SSHKit::SimpleHostParser
  # pkg:gem/sshkit#lib/sshkit/host.rb:205
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:202
  def username; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/host.rb:199
    def suitable?(host_string); end
  end
end

# @private
#
# pkg:gem/sshkit#lib/sshkit/host.rb:128
class SSHKit::IPv6HostParser < ::SSHKit::SimpleHostParser
  # pkg:gem/sshkit#lib/sshkit/host.rb:137
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:133
  def port; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/host.rb:129
    def suitable?(host_string); end
  end
end

# @private
#
# pkg:gem/sshkit#lib/sshkit/host.rb:177
class SSHKit::IPv6HostWithPortParser < ::SSHKit::SimpleHostParser
  # pkg:gem/sshkit#lib/sshkit/host.rb:190
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:184
  def port; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/host.rb:180
    def suitable?(host_string); end
  end
end

# pkg:gem/sshkit#lib/sshkit/host.rb:178
SSHKit::IPv6HostWithPortParser::IPV6_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/sshkit#lib/sshkit/log_message.rb:3
class SSHKit::LogMessage
  # pkg:gem/sshkit#lib/sshkit/log_message.rb:5
  def initialize(verbosity, message); end

  # pkg:gem/sshkit#lib/sshkit/log_message.rb:4
  def message; end

  # pkg:gem/sshkit#lib/sshkit/log_message.rb:8
  def to_s; end

  # pkg:gem/sshkit#lib/sshkit/log_message.rb:4
  def verbosity; end
end

# pkg:gem/sshkit#lib/sshkit/logger.rb:2
class SSHKit::Logger; end

# pkg:gem/sshkit#lib/sshkit/logger.rb:3
SSHKit::Logger::DEBUG = T.let(T.unsafe(nil), Integer)

# pkg:gem/sshkit#lib/sshkit/logger.rb:6
SSHKit::Logger::ERROR = T.let(T.unsafe(nil), Integer)

# pkg:gem/sshkit#lib/sshkit/logger.rb:7
SSHKit::Logger::FATAL = T.let(T.unsafe(nil), Integer)

# pkg:gem/sshkit#lib/sshkit/logger.rb:4
SSHKit::Logger::INFO = T.let(T.unsafe(nil), Integer)

# pkg:gem/sshkit#lib/sshkit/logger.rb:5
SSHKit::Logger::WARN = T.let(T.unsafe(nil), Integer)

# pkg:gem/sshkit#lib/sshkit/mapping_interaction_handler.rb:3
class SSHKit::MappingInteractionHandler
  # pkg:gem/sshkit#lib/sshkit/mapping_interaction_handler.rb:5
  def initialize(mapping, log_level = T.unsafe(nil)); end

  # pkg:gem/sshkit#lib/sshkit/mapping_interaction_handler.rb:21
  def on_data(_command, stream_name, data, channel); end

  private

  # pkg:gem/sshkit#lib/sshkit/mapping_interaction_handler.rb:42
  def log(message); end
end

# pkg:gem/sshkit#lib/sshkit/host.rb:210
SSHKit::PARSERS = T.let(T.unsafe(nil), Array)

# Used for redaction of a certain argument
#
# pkg:gem/sshkit#lib/sshkit.rb:25
module SSHKit::Redaction; end

# pkg:gem/sshkit#lib/sshkit/exception.rb:3
module SSHKit::Runner; end

# pkg:gem/sshkit#lib/sshkit/runners/abstract.rb:5
class SSHKit::Runner::Abstract
  # pkg:gem/sshkit#lib/sshkit/runners/abstract.rb:9
  def initialize(hosts, options = T.unsafe(nil), &block); end

  # pkg:gem/sshkit#lib/sshkit/runners/abstract.rb:7
  def block; end

  # pkg:gem/sshkit#lib/sshkit/runners/abstract.rb:7
  def hosts; end

  # pkg:gem/sshkit#lib/sshkit/runners/abstract.rb:7
  def options; end

  private

  # pkg:gem/sshkit#lib/sshkit/runners/abstract.rb:17
  def backend(host, &block); end
end

# pkg:gem/sshkit#lib/sshkit/exception.rb:5
class SSHKit::Runner::ExecuteError < ::SSHKit::StandardError
  # pkg:gem/sshkit#lib/sshkit/exception.rb:8
  def initialize(cause); end

  # pkg:gem/sshkit#lib/sshkit/exception.rb:6
  def cause; end
end

# pkg:gem/sshkit#lib/sshkit/runners/group.rb:5
class SSHKit::Runner::Group < ::SSHKit::Runner::Sequential
  # pkg:gem/sshkit#lib/sshkit/runners/group.rb:8
  def initialize(hosts, options = T.unsafe(nil), &block); end

  # pkg:gem/sshkit#lib/sshkit/runners/group.rb:13
  def execute; end

  # pkg:gem/sshkit#lib/sshkit/runners/group.rb:6
  def group_size; end

  # pkg:gem/sshkit#lib/sshkit/runners/group.rb:6
  def group_size=(_arg0); end
end

# pkg:gem/sshkit#lib/sshkit/runners/null.rb:5
class SSHKit::Runner::Null < ::SSHKit::Runner::Abstract
  # pkg:gem/sshkit#lib/sshkit/runners/null.rb:7
  def execute; end
end

# pkg:gem/sshkit#lib/sshkit/runners/parallel.rb:5
class SSHKit::Runner::Parallel < ::SSHKit::Runner::Abstract
  # pkg:gem/sshkit#lib/sshkit/runners/parallel.rb:6
  def execute; end
end

# pkg:gem/sshkit#lib/sshkit/runners/sequential.rb:5
class SSHKit::Runner::Sequential < ::SSHKit::Runner::Abstract
  # pkg:gem/sshkit#lib/sshkit/runners/sequential.rb:8
  def initialize(hosts, options = T.unsafe(nil), &block); end

  # pkg:gem/sshkit#lib/sshkit/runners/sequential.rb:13
  def execute; end

  # pkg:gem/sshkit#lib/sshkit/runners/sequential.rb:6
  def wait_interval; end

  # pkg:gem/sshkit#lib/sshkit/runners/sequential.rb:6
  def wait_interval=(_arg0); end

  private

  # pkg:gem/sshkit#lib/sshkit/runners/sequential.rb:27
  def run_backend(host, &block); end
end

# @private
#
# pkg:gem/sshkit#lib/sshkit/host.rb:98
class SSHKit::SimpleHostParser
  # pkg:gem/sshkit#lib/sshkit/host.rb:104
  def initialize(host_string); end

  # pkg:gem/sshkit#lib/sshkit/host.rb:120
  def attributes; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:116
  def hostname; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:112
  def port; end

  # pkg:gem/sshkit#lib/sshkit/host.rb:108
  def username; end

  class << self
    # pkg:gem/sshkit#lib/sshkit/host.rb:100
    def suitable?(host_string); end
  end
end

# pkg:gem/sshkit#lib/sshkit.rb:3
class SSHKit::StandardError < ::StandardError; end

# pkg:gem/sshkit#lib/sshkit/host.rb:6
class SSHKit::UnparsableHostStringError < ::SSHKit::StandardError; end
